FROM golang:1.24.2-alpine AS builder
WORKDIR /app
COPY . .
#COPY go.mod .

RUN <<EOF
go mod download
go mod tidy 
go build -o web-chat-bot
EOF

FROM scratch
WORKDIR /app
COPY --from=builder /app/web-chat-bot .

CMD ["./web-chat-bot"]